### ISSUE TITLE
Rewrite in Lisp

### ISSUE THREAD

**Issue by alphapapa** [raxod502/dotman#2]
Hey man, seems like you accidentally left this item off your to-do list, so I thought I'd help you out.  ;)  Guile might be a good choice...

**Comment by raxod502** [comment]
Well, as you can see in the [`feat/rewrite` branch](https://github.com/raxod502/dotman/tree/feat/rewrite), I'm actually rewriting it in Python. I think this will be the best choice, since I have a lot of experience with creating simple command-line applications in Python ([eTunes](https://github.com/raxod502/etunes), [diary-manager](https://github.com/raxod502/diary-manager), [acc](https://github.com/raxod502/acc)), and I'd like to get this project up and running quickly.

If I were to use a cooler language, let's be honest—I'd choose Haskell.

**Comment by alphapapa** [comment]
What, Haskell?!  Come on, man, homoiconicity and macros, or die! D=

Haha seriously though, I was looking at *Let Over Lambda* again today, and the ` CL-PPCRE` package and his reader macros for it look so cool. 

BTW, I recently discovered TXR. I'm very impressed, especially for a relatively young language. And the man page/manual is really good. I'm thinking that it might be unusually easy to make a parser for Org files in it, to do fast searching of them outside Emacs. Take a look if you haven't seen it. I just hope it gets packaged for Debian one of these days.

**Comment by raxod502** [comment]
I'll keep those things in mind, thanks for the pointers.
